### ISSUE TITLE
Cmake version agreement

### ISSUE THREAD

**Issue by hctilf** [SIMFORdev/simfor#2]
Предлагаю опустить основную версию cmake до 3,21 или 3,22, т.к. в репозитория lts ubuntu/deb лежат версии 3,22. Т.е. сейчас нужно вручную всё ставить, что не очень удобно + мы вроде бы новых фич и новых версий не используем(если не так, то поправь)?

Также в CMakeLists.txt и examples/CMakeLists.txt стоит версия 3.21, что отличается от README.

Если согласен, то измени это в README.

**Comment by vadim8960** [comment]
Давай до 3.21 понизим. Не вижу проблем в этом. Изменения внесу завтра

**Comment by vadim8960** [comment]
https://github.com/SIMFORdev/simfor/commit/c91d36ffa736a079c0284a0afcb50b89547c5966
